version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install --user awscli
      - pip install --user aws-sam-cli
  build:
    commands:
      # step function deploy
      # - aws cloudformation package --template-file $(pwd)/mlops-pipeline.yml --s3-bucket $PIPELINE_BUCKET --s3-prefix abalone-pipeline/artifacts --output-template-file mlops-pipeline-output.yml
      - sam build --template $(pwd)/template.yaml
      - sam deploy --template-file .aws-sam/build/template.yaml --stack-name aws-mlops-pipeline-abalone --capabilities CAPABILITY_NAMED_IAM --s3-bucket $BUCKET --s3-prefix deployements --no-fail-on-empty-changeset
  post_build:
    commands:
      # invoke setup lambda to add production model performance in DDB table
      # - aws cloudformation create-stack --stack-name abalone-pipeline --template-body $(pwd)/mlops-pipeline-output.yml --parameters $(printf "$parameters" "abalone" "latest" "abalone" "MLOps") --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND 
      - aws lambda invoke --function-name set_inital_table response.json

